// AeroForge - Game Data & Constants

const GAME_DATA = {
  // Tick timing
  TICK_INTERVAL_MS: 2000,   // 2 seconds per tick
  TICKS_PER_MONTH: 4,
  TICKS_PER_YEAR: 48,
  START_YEAR: 2024,
  START_CASH: 500000,

  // Grid
  GRID_COLS: 12,
  GRID_ROWS: 8,
  CELL_SIZE: 80,

  // Contract pool refresh
  CONTRACT_REFRESH_TICKS: 8,
  CONTRACT_POOL_SIZE: 5,

  // Event timing
  EVENT_MIN_TICKS: 30,
  EVENT_MAX_TICKS: 60,

  // XP requirements per level (cumulative)
  LEVEL_XP: [0, 100, 250, 500, 900, 1500, 2500, 4000, 6000, 9000, 13000, 18000, 25000, 35000, 50000],

  // Level titles
  LEVEL_TITLES: [
    '', // placeholder for index 0
    'Startup',
    'Startup',
    'Startup',
    'Small Manufacturer',
    'Small Manufacturer',
    'Small Manufacturer',
    'Established Manufacturer',
    'Established Manufacturer',
    'Established Manufacturer',
    'Tier 2 Supplier',
    'Tier 2 Supplier',
    'Tier 2 Supplier',
    'Tier 1 Supplier',
    'Tier 1 Supplier',
    'OEM'
  ],

  // Max simultaneous contracts by level
  MAX_CONTRACTS_BY_LEVEL: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5],

  // Buildings
  BUILDINGS: {
    admin_hq: {
      id: 'admin_hq',
      name: 'Admin HQ',
      emoji: '🏢',
      color: '#2d6a8f',
      cost: 25000,
      upkeep: 2000,
      description: 'Corporate headquarters. Required to unlock all other buildings.',
      capacity: 0,
      workers: 2,
      effect: 'Unlocks all buildings. +5% contract revenue.',
      maxLevel: 3,
      upgradeCost: [25000, 50000, 100000],
      upgradeEffect: ['Unlock all buildings', '+10% revenue', '+20% revenue, +1 contract slot'],
      requires: [],
      maxCount: 1,
    },
    assembly_bay: {
      id: 'assembly_bay',
      name: 'Assembly Bay',
      emoji: '🏭',
      color: '#1e7a4f',
      cost: 50000,
      upkeep: 4000,
      description: 'Main production floor. Assembles components and fulfills contracts.',
      capacity: 10,
      workers: 5,
      effect: '+10 production capacity/tick',
      maxLevel: 3,
      upgradeCost: [50000, 100000, 200000],
      upgradeEffect: ['+10 capacity', '+25 capacity, +2 workers', '+50 capacity, unlock advanced assembly'],
      requires: ['admin_hq'],
      maxCount: 4,
    },
    machine_shop: {
      id: 'machine_shop',
      name: 'Machine Shop',
      emoji: '⚙️',
      color: '#5a4a1e',
      cost: 75000,
      upkeep: 6000,
      description: 'Precision machining for parts and components.',
      capacity: 8,
      workers: 4,
      effect: '+8 production capacity. Required for Growth contracts.',
      maxLevel: 3,
      upgradeCost: [75000, 150000, 300000],
      upgradeEffect: ['+8 capacity', '+20 capacity, precision bonus', '+40 capacity, CNC automation'],
      requires: ['admin_hq'],
      maxCount: 3,
    },
    quality_lab: {
      id: 'quality_lab',
      name: 'Quality Lab',
      emoji: '🔬',
      color: '#2d4a8f',
      cost: 100000,
      upkeep: 7000,
      description: 'Quality assurance and inspection facility.',
      capacity: 0,
      workers: 3,
      effect: '+20% contract success rate. Required for Tier 2+ contracts.',
      maxLevel: 3,
      upgradeCost: [100000, 200000, 400000],
      upgradeEffect: ['+20% success', '+35% success, reduce penalties', '+50% success, ISO certification'],
      requires: ['admin_hq'],
      maxCount: 2,
    },
    warehouse: {
      id: 'warehouse',
      name: 'Warehouse',
      emoji: '📦',
      color: '#6b3a1e',
      cost: 30000,
      upkeep: 2000,
      description: 'Material storage and supply chain buffer.',
      capacity: 5,
      workers: 2,
      effect: '+5 capacity buffer. Reduces supply chain risk.',
      maxLevel: 3,
      upgradeCost: [30000, 60000, 120000],
      upgradeEffect: ['+5 buffer', '+15 buffer, automated inventory', '+30 buffer, just-in-time delivery'],
      requires: ['admin_hq'],
      maxCount: 4,
    },
    rd_center: {
      id: 'rd_center',
      name: 'R&D Center',
      emoji: '🧪',
      color: '#4a1e7a',
      cost: 200000,
      upkeep: 12000,
      description: 'Research & development. Unlocks technologies and contract types.',
      capacity: 0,
      workers: 8,
      effect: '+3 research points/tick. Unlocks advanced contracts.',
      maxLevel: 3,
      upgradeCost: [200000, 400000, 800000],
      upgradeEffect: ['+3 research/tick', '+8 research/tick, patent bonus', '+15 research/tick, breakthrough tech'],
      requires: ['admin_hq', 'quality_lab'],
      maxCount: 2,
    },
    hr_office: {
      id: 'hr_office',
      name: 'HR Office',
      emoji: '👥',
      color: '#1e5a6b',
      cost: 40000,
      upkeep: 3000,
      description: 'Human resources management.',
      capacity: 0,
      workers: 2,
      effect: '+15% worker efficiency. Reduces upkeep costs.',
      maxLevel: 3,
      upgradeCost: [40000, 80000, 160000],
      upgradeEffect: ['+15% efficiency', '+25% efficiency, training', '+40% efficiency, talent pipeline'],
      requires: ['admin_hq'],
      maxCount: 1,
    },
    clean_room: {
      id: 'clean_room',
      name: 'Clean Room',
      emoji: '✨',
      color: '#1a4a5a',
      cost: 150000,
      upkeep: 10000,
      description: 'ISO Class 7 clean room for avionics and space components.',
      capacity: 6,
      workers: 4,
      effect: '+6 capacity. Required for avionics/space contracts.',
      maxLevel: 3,
      upgradeCost: [150000, 300000, 600000],
      upgradeEffect: ['+6 capacity', '+15 capacity, ISO Class 5', '+30 capacity, space-rated'],
      requires: ['admin_hq', 'quality_lab'],
      maxCount: 2,
    },
    test_facility: {
      id: 'test_facility',
      name: 'Test Facility',
      emoji: '🛠️',
      color: '#5a1e1e',
      cost: 125000,
      upkeep: 8000,
      description: 'Product testing and validation facility.',
      capacity: 0,
      workers: 3,
      effect: '-25% contract failure rate. Boosts reputation.',
      maxLevel: 3,
      upgradeCost: [125000, 250000, 500000],
      upgradeEffect: ['-25% failure', '-40% failure, environmental testing', '-55% failure, full certification suite'],
      requires: ['admin_hq', 'machine_shop'],
      maxCount: 2,
    },
    runway: {
      id: 'runway',
      name: 'Runway/Tarmac',
      emoji: '✈️',
      color: '#2d2d2d',
      cost: 300000,
      upkeep: 15000,
      description: 'Flight line and tarmac for aircraft delivery and testing.',
      capacity: 0,
      workers: 6,
      effect: 'Unlocks military & commercial aircraft contracts.',
      maxLevel: 2,
      upgradeCost: [300000, 600000],
      upgradeEffect: ['Unlock aircraft contracts', 'Extended runway, heavy aircraft'],
      requires: ['admin_hq', 'test_facility'],
      maxCount: 1,
    },
  },

  // Research techs
  TECHS: {
    lean_manufacturing: {
      id: 'lean_manufacturing',
      name: 'Lean Manufacturing',
      cost: 50,
      description: 'Reduce upkeep costs by 10%.',
      effect: { upkeepReduction: 0.10 },
    },
    advanced_machining: {
      id: 'advanced_machining',
      name: 'Advanced Machining',
      cost: 80,
      description: 'Machine Shop capacity +50%.',
      effect: { machineShopBonus: 0.50 },
    },
    quality_control: {
      id: 'quality_control',
      name: 'Quality Control',
      cost: 60,
      description: 'Contract success rate +10%.',
      effect: { successBonus: 0.10 },
    },
    supply_chain_opt: {
      id: 'supply_chain_opt',
      name: 'Supply Chain Optimization',
      cost: 70,
      description: 'Reduce material costs by 15%.',
      effect: { materialCostReduction: 0.15 },
    },
    digital_twin: {
      id: 'digital_twin',
      name: 'Digital Twin Simulation',
      cost: 120,
      description: 'Contract duration -20% (faster delivery).',
      effect: { durationReduction: 0.20 },
    },
    composite_materials: {
      id: 'composite_materials',
      name: 'Composite Materials',
      cost: 150,
      description: 'Unlock composite component contracts. +15% revenue on all contracts.',
      effect: { revenueBonus: 0.15 },
    },
    automation: {
      id: 'automation',
      name: 'Factory Automation',
      cost: 200,
      description: 'All buildings +25% capacity. Worker costs -20%.',
      effect: { capacityBonus: 0.25, workerCostReduction: 0.20 },
    },
    as9100: {
      id: 'as9100',
      name: 'AS9100 Certification',
      cost: 100,
      description: 'Unlock premium tier contracts. Reputation +2.',
      effect: { unlockPremium: true, reputationBonus: 2 },
    },
  }
};
