// AeroForge - Game Data & Constants

const GAME_DATA = {
  // Tick timing
  TICK_INTERVAL_MS: 2000,   // 2 seconds per tick
  TICKS_PER_MONTH: 4,
  TICKS_PER_YEAR: 48,
  START_YEAR: 2024,
  START_CASH: 500000,

  // Grid
  GRID_COLS: 12,
  GRID_ROWS: 8,
  CELL_SIZE: 80,

  // Contract pool refresh
  CONTRACT_REFRESH_TICKS: 8,
  CONTRACT_POOL_SIZE: 5,

  // Event timing
  EVENT_MIN_TICKS: 30,
  EVENT_MAX_TICKS: 60,

  // XP requirements per level (cumulative)
  LEVEL_XP: [0, 100, 300, 700, 1400, 2500, 4000, 6500, 10000, 15000, 22000, 32000, 45000, 62000, 83000, 110000],

  // Level titles
  LEVEL_TITLES: [
    '',
    'Startup',
    'Startup',
    'Startup',
    'Small Manufacturer',
    'Small Manufacturer',
    'Small Manufacturer',
    'Established Manufacturer',
    'Established Manufacturer',
    'Established Manufacturer',
    'Tier 2 Supplier',
    'Tier 2 Supplier',
    'Tier 2 Supplier',
    'Tier 1 Supplier',
    'Tier 1 Supplier',
    'OEM'
  ],

  // Max simultaneous contracts by level
  MAX_CONTRACTS_BY_LEVEL: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6, 7, 8],

  // Buildings
  BUILDINGS: {
    admin_hq: {
      id: 'admin_hq',
      name: 'Admin HQ',
      emoji: '🏢',
      color: '#2d6a8f',
      cost: 25000,
      upkeep: 2000,
      description: 'Corporate headquarters. Required to unlock all other buildings.',
      capacity: 0,
      workers: 2,
      effect: 'Unlocks all buildings. +5% contract revenue.',
      maxLevel: 3,
      upgradeCost: [40000, 80000],
      upgradeEffect: ['+10% revenue, +admin capacity', '+20% revenue, +1 contract slot'],
      requires: [],
      maxCount: 1,
      learnMore: '📚 Your HQ manages your Quality Management System (QMS), ITAR compliance program, and all regulatory approvals. AS9100 — the aerospace quality standard — is audited here. Companies without a robust QMS cannot win Boeing or Airbus contracts. The QMS covers document control, corrective actions, and customer focus requirements.',
    },
    assembly_bay: {
      id: 'assembly_bay',
      name: 'Assembly Bay',
      emoji: '🏭',
      color: '#1e7a4f',
      cost: 50000,
      upkeep: 4000,
      description: 'Main production floor. Assembles components and fulfills contracts.',
      capacity: 10,
      workers: 5,
      effect: '+10 production capacity/tick',
      maxLevel: 3,
      upgradeCost: [75000, 150000],
      upgradeEffect: ['+15 capacity total', '+28 capacity total, advanced assembly'],
      requires: ['admin_hq'],
      maxCount: 4,
      learnMore: '📚 Aerospace assembly bays use "traveler" documents — job cards that follow each part through every operation. Every torque, seal, and installation step is signed off. Assembly is often the longest phase: a Boeing 737 fuselage section takes ~3 weeks to assemble from machined parts. Tooling fixtures (jigs) hold parts in exact position during assembly.',
    },
    machine_shop: {
      id: 'machine_shop',
      name: 'Machine Shop',
      emoji: '⚙️',
      color: '#5a4a1e',
      cost: 75000,
      upkeep: 6000,
      description: 'Precision machining for parts and components.',
      capacity: 8,
      workers: 4,
      effect: '+8 production capacity. Required for Growth contracts.',
      maxLevel: 3,
      upgradeCost: [110000, 220000],
      upgradeEffect: ['+12 capacity total', '+22 capacity total, CNC automation'],
      requires: ['admin_hq'],
      maxCount: 3,
      learnMore: '📚 Aerospace machining holds tolerances of ±0.0005" (half a thousandth of an inch). 5-axis CNC mills can machine complex curved surfaces in one setup — critical for impellers and structural brackets. Coolant management, vibration control, and tool wear monitoring separate good aerospace shops from the rest. A single 5-axis machining center costs $400K–$2M.',
    },
    quality_lab: {
      id: 'quality_lab',
      name: 'Quality Lab',
      emoji: '🔬',
      color: '#2d4a8f',
      cost: 100000,
      upkeep: 7000,
      description: 'Quality assurance and inspection facility.',
      capacity: 0,
      workers: 3,
      effect: '+20% contract success rate. Reduces scrap rate. Required for Tier 2+ contracts.',
      maxLevel: 3,
      upgradeCost: [150000, 300000],
      upgradeEffect: ['+35% success total, lower scrap', '+55% success total, ISO certification'],
      requires: ['admin_hq'],
      maxCount: 2,
      learnMore: '📚 Aerospace quality labs contain Coordinate Measuring Machines (CMMs) that scan parts in 3D to verify they match the CAD model. Dye penetrant and magnetic particle inspection find surface cracks. Hardness testers verify heat treatment. AS9100 requires a documented calibration program — every gauge must be traceable to NIST standards. Calibration records are audited regularly.',
    },
    warehouse: {
      id: 'warehouse',
      name: 'Warehouse',
      emoji: '📦',
      color: '#6b3a1e',
      cost: 30000,
      upkeep: 2000,
      description: 'Material storage and supply chain buffer.',
      capacity: 5,
      workers: 2,
      effect: '+5 capacity buffer. Reduces supply chain risk.',
      maxLevel: 3,
      upgradeCost: [45000, 90000],
      upgradeEffect: ['+10 buffer total', '+20 buffer total, just-in-time delivery'],
      requires: ['admin_hq'],
      maxCount: 4,
      learnMore: '📚 Aerospace material storage has strict requirements: alloys must be temperature/humidity controlled, composites pre-preg materials are frozen, and chemicals have shelf-life limits. Every material must have traceability back to a mill certificate. A "stock-out" — running out of material mid-contract — can force a costly schedule slip. Proper inventory management (often ERP-driven) is essential.',
    },
    rd_center: {
      id: 'rd_center',
      name: 'R&D Center',
      emoji: '🧪',
      color: '#4a1e7a',
      cost: 200000,
      upkeep: 12000,
      description: 'Research & development. Unlocks technologies and contract types.',
      capacity: 0,
      workers: 8,
      effect: '+3 research points/tick. Unlocks advanced contracts.',
      maxLevel: 3,
      upgradeCost: [300000, 600000],
      upgradeEffect: ['+6 research/tick total', '+12 research/tick total, breakthrough tech'],
      requires: ['admin_hq', 'quality_lab'],
      maxCount: 2,
      learnMore: '📚 Aerospace R&D often qualifies for the federal R&D Tax Credit (26 USC §41), which can offset 6–8% of qualifying research expenses. Companies also use SBIR/STTR grants from DoD and NASA to fund early-stage technology development — essentially free money for R&D if you win. R&D investment is how Tier 2 suppliers climb into Tier 1: by owning proprietary processes competitors can\'t replicate.',
    },
    hr_office: {
      id: 'hr_office',
      name: 'HR Office',
      emoji: '👥',
      color: '#1e5a6b',
      cost: 40000,
      upkeep: 3000,
      description: 'Human resources management.',
      capacity: 0,
      workers: 2,
      effect: '+15% worker efficiency. Reduces upkeep costs.',
      maxLevel: 3,
      upgradeCost: [60000, 120000],
      upgradeEffect: ['+25% efficiency total', '+40% efficiency total, talent pipeline'],
      requires: ['admin_hq'],
      maxCount: 1,
      learnMore: '📚 Skilled aerospace workers are hard to find — A&P mechanics, CMM programmers, NDT Level II inspectors, and certified welders (AWS D17.1) command premium wages. Many aerospace manufacturers partner with community colleges for apprenticeship programs. High turnover is extremely costly: an experienced CNC machinist takes 2–3 years to become fully productive on tight-tolerance aerospace work.',
    },
    clean_room: {
      id: 'clean_room',
      name: 'Clean Room',
      emoji: '✨',
      color: '#1a4a5a',
      cost: 150000,
      upkeep: 10000,
      description: 'ISO Class 7 clean room for avionics and space components.',
      capacity: 6,
      workers: 4,
      effect: '+6 capacity. Reduces scrap rate. Required for avionics/space contracts.',
      maxLevel: 3,
      upgradeCost: [225000, 450000],
      upgradeEffect: ['+15 capacity total, ISO Class 5', '+30 capacity total, space-rated'],
      requires: ['admin_hq', 'quality_lab'],
      maxCount: 2,
      learnMore: '📚 Clean rooms control particulate contamination measured in particles-per-cubic-foot. ISO Class 7 (formerly Class 10,000) allows 10,000 particles ≥0.5μm per cubic foot. Avionics, inertial sensors, and space hardware require this because a single dust particle can short-circuit a flight computer or jam a precision gyroscope. Gowning protocols, HEPA filtration, and positive air pressure are all required.',
    },
    test_facility: {
      id: 'test_facility',
      name: 'Test Facility',
      emoji: '🛠️',
      color: '#5a1e1e',
      cost: 125000,
      upkeep: 8000,
      description: 'Product testing and validation facility.',
      capacity: 0,
      workers: 3,
      effect: '-25% contract failure rate. Reduces scrap. Boosts reputation.',
      maxLevel: 3,
      upgradeCost: [185000, 375000],
      upgradeEffect: ['-40% failure total, better scrap', '-55% failure total, full certification suite'],
      requires: ['admin_hq', 'machine_shop'],
      maxCount: 2,
      learnMore: '📚 Aerospace test facilities run Acceptance Test Procedures (ATPs) — documented tests every unit must pass before delivery. Tests include proof pressure, vibration, thermal cycling, and electrical functional tests. For structural parts, static and fatigue testing proves the design meets safety factors. A dedicated test facility also enables you to conduct DT&E (Development Test & Evaluation) for new contract types.',
    },
    runway: {
      id: 'runway',
      name: 'Runway/Tarmac',
      emoji: '✈️',
      color: '#2d2d2d',
      cost: 300000,
      upkeep: 15000,
      description: 'Flight line and tarmac for aircraft delivery and testing.',
      capacity: 0,
      workers: 6,
      effect: 'Unlocks military & commercial aircraft contracts.',
      maxLevel: 2,
      upgradeCost: [500000],
      upgradeEffect: ['Extended runway, heavy aircraft contracts'],
      requires: ['admin_hq', 'test_facility'],
      maxCount: 1,
      learnMore: '📚 A flight line (the area where aircraft are parked, serviced, and taxied) is needed for final assembly and acceptance testing of complete aircraft. Flight test programs follow a detailed test card sequence — ground runs, taxi tests, then first flight. FAA Production Flight Test (PFT) is required before airworthiness certificate issuance on each new aircraft.',
    },
  },

  // Research techs
  TECHS: {
    lean_manufacturing: {
      id: 'lean_manufacturing',
      name: 'Lean Manufacturing',
      cost: 50,
      description: 'Reduce upkeep costs by 10%.',
      effect: { upkeepReduction: 0.10 },
    },
    advanced_machining: {
      id: 'advanced_machining',
      name: 'Advanced Machining',
      cost: 80,
      description: 'Machine Shop capacity +50%.',
      effect: { machineShopBonus: 0.50 },
    },
    quality_control: {
      id: 'quality_control',
      name: 'Quality Control',
      cost: 60,
      description: 'Contract success rate +10%.',
      effect: { successBonus: 0.10 },
    },
    supply_chain_opt: {
      id: 'supply_chain_opt',
      name: 'Supply Chain Opt.',
      cost: 70,
      description: 'Reduce material costs by 15%.',
      effect: { materialCostReduction: 0.15 },
    },
    digital_twin: {
      id: 'digital_twin',
      name: 'Digital Twin',
      cost: 120,
      description: 'Contract duration -20% (faster delivery).',
      effect: { durationReduction: 0.20 },
    },
    composite_materials: {
      id: 'composite_materials',
      name: 'Composite Materials',
      cost: 150,
      description: '+15% revenue on all contracts.',
      effect: { revenueBonus: 0.15 },
    },
    automation: {
      id: 'automation',
      name: 'Factory Automation',
      cost: 200,
      description: 'All buildings +25% capacity. Worker costs -20%.',
      effect: { capacityBonus: 0.25, workerCostReduction: 0.20 },
    },
    as9100: {
      id: 'as9100',
      name: 'AS9100 Certification',
      cost: 100,
      description: 'Unlock premium tier contracts. Reputation +2.',
      effect: { unlockPremium: true, reputationBonus: 2 },
    },
  }
};
